import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';

import 'injection.config.dart';

final GetIt getIt = GetIt.instance;

/// Generated by `injectable_generator` — run `build_runner` (see
/// mobile/README.md) to produce `injection.config.dart` before this
/// file will compile. It scans every `@injectable`/`@lazySingleton`/
/// `@LazySingleton(as: ...)` annotated class under `lib/` and wires it
/// into [getIt].
@InjectableInit(
  initializerName: 'init',
  preferRelativeImports: true,
  asExtension: false,
)
Future<void> configureDependencies() async => getIt.init();
